### ISSUE TITLE
Looking forward to trying this on some monophase GB segmentation!

### ISSUE THREAD

**Issue by sgbaird** [nasa/pretrained-microscopy-models#1]
Great presentation at the TechBlick virtual conf

**Comment by JStuckner** [comment]
Thanks! It was nice meeting you. Let me know if you run into any issues. I'd be curious if the models can be embedded in the diffusion models you're looking into.

**Comment by sgbaird** [comment]
> Thanks! It was nice meeting you.

@JStuckner great to meet you, too! Love the gh profile pic with your kiddo btw.

> Let me know if you run into any issues.

Will do!

> I'd be curious if the models can be embedded in the diffusion models you're looking into.

A few resources that might be good discussion/starting points:
- https://github.com/heejkoo/Awesome-Diffusion-Models#segmentation
- https://github.com/search?q=ddpm+segmentation (e.g. https://github.com/yandex-research/ddpm-segmentation)
- https://www.google.com/search?q=diffusion+segmentation
- https://github.com/txie-93/cdvae
- The image-to-image usage of [imagen-pytorch](https://github.com/lucidrains/imagen-pytorch)

I'm not sure how the existing pretrained models could be integrated directly with a diffusion model; however, I think it would be straightforward to train a model like [`ddpm-segmentation`](https://github.com/yandex-research/ddpm-segmentation) on the original training data.

cc @oliverkjohnson

**Comment by sgbaird** [comment]
cc @faris-k, segmentation might be worth trying for your problem where classes == failure mode

**Comment by JStuckner** [comment]
Very interesting. Thanks for sharing these resources! Looking at [ddpm-segmentation](https://github.com/yandex-research/ddpm-segmentation), I agree that it should be pretty straightforward to pre-train a DDPM model using [guided-diffusion](https://github.com/openai/guided-diffusion) on MicroNet and see how it performs on segmentation. Since their ddpm-segmentation model pulls features from every scale of U-Net, I wonder if it would work especially well on microscopy data which often has multiscale features.
